### PR TITLE
corpuz-branch

### PR DESCRIPTION
**Pull request by ABCorpuz**

### CODE REVIEW

**Review by ABCorpuz — COMMENTED** [review]
this is leg8

**Comment by amillet2001** [comment]
29/30, one conflict detected - calculator.java is not a unique filename github merge approved - rename the file next time

**Comment by amillet2001** [comment]
@

**Comment by amillet2001** [comment]
29/30, one conflict detected - calculator.java is not a unique filename github merge approved - rename the file next time

**Pull request merged**
